# Generated by Django 5.1.6 on 2025-07-01 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_core', '0008_coursefeedback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursefeedback',
            options={'ordering': ['-created_at'], 'verbose_name': 'Umpan Balik', 'verbose_name_plural': 'Umpan Balik'},
        ),
        migrations.AlterUniqueTogether(
            name='coursefeedback',
            unique_together={('member',)},
        ),
        migrations.AddField(
            model_name='coursefeedback',
            name='member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='course_feedbacks', to='lms_core.coursemember', verbose_name='Anggota Kursus'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coursefeedback',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Dibuat pada'),
        ),
        migrations.AlterField(
            model_name='coursefeedback',
            name='feedback',
            field=models.TextField(verbose_name='Umpan Balik'),
        ),
        migrations.AlterField(
            model_name='coursefeedback',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Diperbarui pada'),
        ),
        migrations.RemoveField(
            model_name='coursefeedback',
            name='course',
        ),
        migrations.RemoveField(
            model_name='coursefeedback',
            name='user',
        ),
    ]
