# Generated by Django 5.1.6 on 2025-06-28 10:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_core', '0003_coursecontent_coursemember_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content_id',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='member_id',
            new_name='member',
        ),
        migrations.RenameField(
            model_name='coursecontent',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='coursecontent',
            old_name='parent_id',
            new_name='parent',
        ),
        migrations.RenameField(
            model_name='coursemember',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='coursemember',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='coursemember',
            unique_together={('course', 'user')},
        ),
    ]
