# Generated by Django 5.1.6 on 2025-06-29 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_core', '0006_alter_course_teacher_delete_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursecontent',
            options={'verbose_name': 'Konten Mata Kuliah', 'verbose_name_plural': 'Konten Mata Kuliah'},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='content_id',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='member',
            new_name='member_id',
        ),
        migrations.RenameField(
            model_name='coursemember',
            old_name='course',
            new_name='course_id',
        ),
        migrations.RenameField(
            model_name='coursemember',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AlterUniqueTogether(
            name='coursemember',
            unique_together={('course_id', 'user_id')},
        ),
        migrations.RemoveField(
            model_name='coursecontent',
            name='course',
        ),
        migrations.RemoveField(
            model_name='coursecontent',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='coursecontent',
            name='video_url',
        ),
        migrations.AddField(
            model_name='comment',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Disetujui'),
        ),
        migrations.AddField(
            model_name='course',
            name='max_students',
            field=models.IntegerField(default=30, verbose_name='Jumlah Maksimal Siswa'),
        ),
        migrations.AddField(
            model_name='coursecontent',
            name='course_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='lms_core.course', verbose_name='Mata Kuliah'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursecontent',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='lms_core.coursecontent', verbose_name='Induk Konten'),
        ),
        migrations.AddField(
            model_name='coursecontent',
            name='scheduled_end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Waktu Selesai'),
        ),
        migrations.AddField(
            model_name='coursecontent',
            name='scheduled_start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Waktu Mulai'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nama'),
        ),
        migrations.AlterField(
            model_name='coursecontent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada'),
        ),
        migrations.AlterField(
            model_name='coursecontent',
            name='description',
            field=models.TextField(verbose_name='Deskripsi'),
        ),
        migrations.AlterField(
            model_name='coursecontent',
            name='file_attachment',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Lampiran File'),
        ),
        migrations.AlterField(
            model_name='coursecontent',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nama Konten'),
        ),
        migrations.AlterField(
            model_name='coursecontent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Diperbarui Pada'),
        ),
        migrations.AlterField(
            model_name='coursemember',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms_core.course')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pengumuman',
                'verbose_name_plural': 'Pengumuman',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategori',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='lms_core.category'),
        ),
        migrations.CreateModel(
            name='ContentCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms_core.coursecontent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('content', 'user')},
            },
        ),
    ]
