# Generated by Django 5.1.6 on 2025-07-01 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_core', '0007_alter_coursecontent_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(verbose_name='Umpan Balik')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui pada')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_feedbacks', to='lms_core.coursemember', verbose_name='Anggota Kursus')),
            ],
            options={
                'verbose_name': 'Umpan Balik',
                'verbose_name_plural': 'Umpan Balik',
                'ordering': ['-created_at'],
                'unique_together': {('member',)},
            },
        ),
    ]
