# Generated by Django 5.1.6 on 2025-07-01 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_core', '0009_contentbookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecontent',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Sudah Dipublikasikan'),
        ),
    ]
